[Common]
retryCount = 5
# http or grpc
mode = "http"
# only take effect in gRPC mode. If client lost connection from
# main server or standby server, will reconnect to server every
# reconnectInterval. Also, if client fallback to standby server,
# will retry connect to main server every reconnectInterval.
reconnectInterval = "10m"

[Http.MainServer]
url = "https://acmeserver.example.com:19198/1145141919810"
token = "KFCCrazyThursdayVMe50"

[Http.StandbyServer]
url = "http://mybackupserver.local:11451/1919810"

[GRPC.MainServer]
server = "grpc.example.com:9999"
ca = "/path/to/grpc/mtls/ca.pem"
certificate = "/path/to/grpc/mtls/client/cert.pem"
key = "/path/to/grpc/mtls/client/private.key"

[GRPC.StandbyServer]
server = "192.168.1.2:9090"
ca = "/path/to/grpc/mtls/ca.pem"
certificate = "/path/to/grpc/mtls/client/cert.pem"
key = "/path/to/grpc/mtls/client/private.key"

[[Certifications]]
name = "certFileNameToSave"
savePath = "/path/to/directory/which/saves/your/certifications"
# will save cert and key file at savePath/name.pem and savePath/name.key
domains = [
    "*.example.com",
    "*.mm.example.com",
]
# command to reload your services
# reloadCommand = "systemctl reload nginx"
reloadCommand = "bash /opt/acme/reload.sh"

[[Certifications]]
name = "cert2"
savePath = "/path/to/directory/which/saves/your/certifications"
domains = [
    "*.lulu.com",
    "*.mm.lulu.com",
]
reloadCommand = "bash /opt/acme/reload.sh"
